trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: my-secrets-group   # 👈 Contains DOCKERHUB_USERNAME, DOCKERHUB_TOKEN, PRISMA_API_KEY

jobs:
- job: Scan_And_Copy_Image
  displayName: Scan image with Twistcli and copy if safe
  steps:
  - script: |
      echo "⬇️ Downloading twistcli binary"
      curl -o twistcli https://app0.prismacloud.io/api/v1/util/twistcli
      chmod +x twistcli

      echo "🔐 Logging into Docker Hub"
      echo "$(DOCKERHUB_TOKEN)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin

      echo "📥 Pulling public image"
      docker pull nginx:latest

      echo "🛡️ Scanning image with twistcli"
      ./twistcli images scan \
        --address app0.prismacloud.io \
        --bc-api-key $(PRISMA_API_KEY) \
        nginx:latest

      if [ $? -ne 0 ]; then
        echo "❌ Vulnerabilities found! Aborting pipeline."
        exit 1
      fi

      RANDOM_SUFFIX=$(date +%s)
      TARGET_IMAGE="$(DOCKERHUB_USERNAME)/nginx-clone:copied-$RANDOM_SUFFIX"

      echo "🏷️ Tagging image as $TARGET_IMAGE"
      docker tag nginx:latest $TARGET_IMAGE

      echo "🚀 Pushing image to Docker Hub: $TARGET_IMAGE"
      docker push $TARGET_IMAGE

      echo "✅ Image copied successfully."
    displayName: Scan and Push Docker Image
